### ISSUE TITLE
Asking for help to solve the dependency conflict issues of the polyaxon-schemas's downstream projects

### ISSUE THREAD

**Issue by NeolithEra** [polyaxon/polyaxon-schemas#55]
Hi, a similar issue as #54 , your downstream project **_polyaxon-cli_** suffered from a similar dependency conflict issue caused by polyaxon-schemas 0.5.6.

As shown in the following link [#issue 39](https://github.com/polyaxon/polyaxon-cli/issues/39).

Could you please loosen the version constraint of **_six_**, to remove this dependency hell?

@mouradmourafiq Thanks for your help!

**Comment by mouradmourafiq** [comment]
This will be fixed in the patch release
